### ISSUE TITLE
Update for  OpenWRT 24.10

### ISSUE THREAD

**Issue by roliverio** [4IceG/luci-app-sms-tool#31]
Hi. 

Do you plan to update this app for the upcoming 24.10 OpenWRT version?

Thanks for any info

**Comment by 4IceG** [comment]
Hi,
Package should compile on the current OpenWrt version. 

Another question is why do you want to use package in Lua when the current version is rewritten in JS (https://github.com/4IceG/luci-app-sms-tool-js).

**Comment by siw1973** [comment]
Hi there,

This currently causes a failure on LuCI Attended Sysupgrade for 24.10..7 Is there any way this can be looked at as I really like this tool to be able to see what messages are coming in on a SIM card from vendors.

```
Updated list of available packages in /builder/build_dir/target-mips_24kc_musl/root-ath79/../../../../builder/dl/imagebuilder
Downloading file:packages/Packages.sig
Signature check passed.
Collected errors:
 * opkg_install_cmd: Cannot install package luci-app-sms-tool.
make[2]: *** [Makefile:234: package_install] Error 255
make[1]: *** [Makefile:171: _call_manifest] Error 2
make: *** [Makefile:349: manifest] Error 2

Traceback (most recent call last):
  File "/app/.venv/lib/python3.14/site-packages/rq/worker/base.py", line 1550, in perform_job
    return_value = job.perform()
  File "/app/.venv/lib/python3.14/site-packages/rq/job.py", line 1368, in perform
    self._result = self._execute()
                   ~~~~~~~~~~~~~^^
  File "/app/.venv/lib/python3.14/site-packages/rq/job.py", line 1428, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/app/asu/build.py", line 500, in build
    result = _build(build_request, job)
  File "/app/asu/build.py", line 302, in _build
    report_error(job, check_package_errors(job.meta["stderr"]))
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/asu/util.py", line 338, in report_error
    raise RuntimeError(msg)
RuntimeError: Impossible package selection: missing (luci-app-sms-tool)
```

**EDIT** : Found the luci-app-sms-tool-js but can't see it on the installable packages in 24.10.0, do I need to delete the luci-app-sms-tool, run the upgrade and then sideload ? If I do that will I loose the config that I have done or is it just the interface that get's remove and put back ?

Cheers,


Simon.

**Comment by 4IceG** [comment]
Hi,
@siw1973 I no longer maintain the luci-app-sms-tool package, I recommend installing luci-app-sms-tool-js if possible. The luci-app-sms-tool-js package has a different configuration file and is more advanced, offering many features that luci-app-sms-tool does not have. Uninstall old package and install the new one. Check if you can install sms-tool, because uninstalling luci-app-sms-tool may also remove it.

https://github.com/4IceG/luci-app-sms-tool-js/releases
